# Generated by Django 5.0.6 on 2024-06-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
